#!/bin/bash (borrow from Andre.B and I modify it to fit my needs)
tsv="run_apicomplexa_odb10/full_table.tsv"
for taxa in Ht Pc Pf Pk Pv Py Tg; do

cat ./$taxa/$tsv | grep -w "Complete" | \
 cut -f 1 >> ./all_BUSCO-ID.txt

done
